---
output:
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
    toc: no
    keep_tex: true
    includes:
      in_header: preamble.tex
      before_body: title.tex
# title: "A Pandoc Markdown Article Starter and Template"
# thanks: "Replication files are available on the author's Github account..."
# author:
# date: "`r format(Sys.time(), '%B %d, %Y')`"
# abstract:
#  "This document provides an introduction to R Markdown, argues for its...  \\par \\textbf{Keywords:} one, two, three "
# fontfamily: mathpazo
fontsize: 12
# spacing: double
documentclass: article
# classoption: fleqn
# paper: a4
# csl: ucl-institute-of-education-harvard.csl
bibliography: references.bib
biblio-style: apalike
natbiboptions: round
link-citations: yes
linkcolor: blue!000!black
urlcolor: blue!000!black
citecolor: blue!000!black
linestretch: 1.5
indent: TRUE
---

```{r setup}
#| include=FALSE
options(scipen=999)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      dpi = 500, 
                      fig.pos = "H", 
                      fig.env= 'figure', 
                      tab.topcaption = TRUE,
                      ft.align = "left",
                      ft.tabcolsep= 0, 
                      ft.latex.float = "none"
                      )
library(tidyverse)
library(readr)
library(readxl)
library(zoo)
library(magick)
library(stringi)
library(patchwork)
library(xtable)
library(scales)
library(rvest)
library(rebus)
library(PNWColors)
library(lubridate)
library(here)
library(flextable)
library(gt)
library(officer)
library(officedown)
library(modelsummary)
library(sandwich)
library(lmtest)
library(stargazer)
```

```{r}
#| func
source(here("Functions","flextable_word.R" ))
source(here("Functions","modelsummary_pdf.R" ))
source(here("Functions","borderlines.R" ))

set_flextable_defaults(font.size = 8, 
                       text.align = "left", 
                       font.color = "black", 
                       theme_fun = theme_apa, 
                       padding = 0,
                       line_spacing = 0)
```


# Introduction

# Methodology


# Data


# Empirical Results


# Conclusion

\newpage
# References {.unnumbered}
::: {#refs}
:::


\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}

\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}

\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}

# Appendix
